INSERT INTO ServiceType VALUES(0,'VETERINARIA', 'SERVICIOS MEDICOS VETERINARIOS'),(0,'CERRAJERIA','SERVICIOS DE CERRAJERIA'),(0,'CUIDADO DE MASCOTAS', 'CUIDADO Y ALIMENTACION DE MASCOTAS');

INSERT INTO City VALUES(0,'BOGOTA'),(0,'MEDELLIN');

INSERT INTO Country VALUES(0,'COLOMBIA');

INSERT INTO documenttype VALUES(0,'CEDULA DE CIUDADANIA');